version: '3.1'

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "${HOME}/docker/volumes/pg:/var/lib/postgresql/data"
    environment:
      PG_DATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: password
